server:
  port: 8080

spring:
  application:
    name: demo-spring-mybatis

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: test123456

mybatis:
  config-location: classpath:mybatis-config.xml
  mapper-locations: classpath:mapper/*Repository.xml
  # If not use config-location, can change to this
  #type-aliases-package: org.vipcube.spring.boot.mybatis.domain
