server:
  port: 8080

spring:
  application:
    name: demo-spring-mybatis-plus

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: test123456

  sql:
    init:
      schema-locations: classpath:schema.sql
      data-locations: classpath:data.sql
      username: ${spring.datasource.username}
      password: ${spring.datasource.password}
      mode: never

mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml

logging:
  level:
    root: warn
    org.vipcube.spring.boot.mybatis.mapper: trace
